version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: fitness_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  api-server:
    build:
      context: ./api-server
    container_name: api-server
    ports:
      - "3000:3000"
    volumes:
      - ./api-server:/usr/src/app
      - ./api-server/.env:/usr/src/app/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    command: ["npx", "nodemon", "src/index.js"]
    restart: unless-stopped

  mobile-app:
    build:
      context: ./mobile-app
    container_name: mobile-app
    ports:
      - "19000:19000"   # Expo Go
      - "19001:19001"   # Metro bundler
      - "19002:19002"   # Web arayüzü
    volumes:
      - ./mobile-app:/usr/src/app
      - ./mobile-app/.env:/usr/src/app/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - api-server
    command: ["npx", "expo", "start", "--tunnel", "--clear"]
    restart: unless-stopped

volumes:
  postgres_data: 