version: '3.9'

services:
  api-server:
    build:
      context: ./api-server
    container_name: api-server
    ports:
      - "3000:3000"
    volumes:
      - ./api-server:/usr/src/app
    environment:
      - NODE_ENV=development
      # Buraya .env dosyasındaki değişkenleri ekleyebilirsin veya .env dosyasını mount edebilirsin
    command: ["npx", "nodemon", "src/index.js"]
    restart: unless-stopped

  mobile-app:
    build:
      context: ./mobile-app
    container_name: mobile-app
    ports:
      - "19000:19000"   # Expo Go
      - "19001:19001"   # Metro bundler
      - "19002:19002"   # Web arayüzü
    volumes:
      - ./mobile-app:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - api-server
    command: ["npx", "expo", "start", "--tunnel", "--clear"]
    restart: unless-stopped 